### ISSUE TITLE
你好，我也在关注 spring jpa Specification 的动态查询问题

### ISSUE THREAD

**Issue by h819** [wenhao/jpa-spec#1]
我也写了一个工具，和您实现的功能一致，您参考下。
欢迎交流。

https://github.com/h819/spring-boot/blob/master/h819-commons/src/main/java/org/h819/web/spring/jpa/JpaDynamicSpecificationBuilder.java

**Comment by wenhao** [comment]
写得很好，学习了。

**Comment by mozhuwanjieDEV** [comment]
写的不错啊，学习了

**Comment by wenhao** [comment]
谢谢，相互学习。
