### ISSUE TITLE
or操作报错

### ISSUE THREAD

**Issue by coder-han** [wenhao/jpa-spec#10]
## error
java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name
## code
Specification<MerchantMarketingMember> specification = Specifications.<MerchantMarketingMember>or().
            eq(request.getMerchantMarketingId(),"merchantMarketingId",request.getMerchantMarketingId()).
                eq(StringUtils.isNotEmpty(request.getParam()),"name",request.getParam()).
                eq(StringUtils.isNotEmpty(request.getParam()),"phone",request.getParam()).
                build();
##
``确定name属性是存在的``

**Comment by wenhao** [comment]
把数据库对应的model贴出来看看
