### ISSUE TITLE
如何设置cache

### ISSUE THREAD

**Issue by kehuixu** [wenhao/jpa-spec#12]
在Repository和Entity中都可以设置cache，在用jpa-spec如何设置cache呢？

**Comment by wenhao** [comment]
会尽快解决...

**Comment by wenhao** [comment]
@Cacheable是Spring的功能，跟JPA没关系吧。

**Comment by kehuixu** [comment]
javax.persistence.Cacheable ...?

**Comment by wenhao** [comment]
应该也没啥区别吧，Spring JPA 怎么用这就怎么用。
