### ISSUE TITLE
OneToMany如果想查many端的size 为0怎么办？

### ISSUE THREAD

**Issue by zhoujinliang** [wenhao/jpa-spec#16]
hql：
SELECT u FROM User u WHERE u.status = 1 AND u.appointments IS EMPTY
或者
SELECT u FROM User u WHERE u.status = 1 AND size(u.appointments) = 0

这种语句怎么搞出来?

**Comment by wenhao** [comment]
JPA原来支持，就应该也支持

**Comment by baoqintian** [comment]
下载下来之后，没有pom.xml文件

**Comment by wenhao** [comment]
> 下载下来之后，没有pom.xml文件

没有pom.xml文件，正常，因为这是gradle构建工程。
