### ISSUE TITLE
OR条件查询的问题

### ISSUE THREAD

**Issue by lu920508536** [wenhao/jpa-spec#19]
Specification<UserInfo> spec = Specifications.<UserInfo>or()
				.eq(StringUtils.isNotBlank(userInfo.getPhoneNo()), "phoneNo", userInfo.getPhoneNo())
				.like(StringUtils.isNotBlank(userInfo.getName()), "name", "%" + userInfo.getName() + "%")
				.build();

当我phoneNo和name都为空时，查询的后台sql，显示的where 0 = 1
这是个bug吗？

**Comment by wenhao** [comment]
建议你再看一下，jpa-spec里面没有0=1或者0=0的逻辑。

**Comment by lu920508536** [comment]
我刚才尝试解决了。我用原生的方式解决了，条件都存在时，要返回null才行，不知道是我使用你jar包方式不对，还是你缺少一个判断。谢谢！
/*		Specification<UserInfo> spec = Specifications.<UserInfo>or()
				.eq(StringUtils.isNotBlank(userInfo.getPhoneNo()), "phoneNo", userInfo.getPhoneNo())
				.like(StringUtils.isNotBlank(userInfo.getName()), "name", "%" + userInfo.getName() + "%")
				.build();*/
		Specification<UserInfo> spec = (root, query, cb) -> {
			List<Predicate> list = new ArrayList<>();
			if (StringUtils.isNotBlank(userInfo.getPhoneNo())) {
				list.add(cb.equal(root.get("phoneNo").as(String.class), userInfo.getPhoneNo()));
			}
			if (StringUtils.isNotBlank(userInfo.getName())) {
				list.add(cb.like(root.get("name").as(String.class), "%" + userInfo.getName() + "%"));
			}
			return list.size() == 0 ? null : cb.or(list.toArray(new Predicate[list.size()]));
		};

**Comment by lu920508536** [comment]
都不存在时，返回null

**Comment by wenhao** [comment]
我写个测试测一下，也许底层你用的Spring Data版本比我高导致的。

**Comment by wenhao** [comment]
我写了个测试测了一下，结果where 1=1，是正确的,你可以在EqualTest.java文件里面找到相关测试。
```java
@Test
public void should_be_able_to_find_all_if_all_predicate_are_null() {
        // given
        Person jack = new PersonBuilder()
                .name("Jack")
                .age(18)
                .build();
        Person eric = new PersonBuilder()
                .name("Eric")
                .age(20)
                .build();
        personRepository.save(jack);
        personRepository.save(eric);

        // when
        Specification<Person> specification = Specifications.<Person>and()
                .eq(isNotBlank(EMPTY), "name", jack.getName())
                .like(isNotBlank(EMPTY), "name", "%" + jack.getName() + "%")
                .build();

        List<Person> persons = personRepository.findAll(specification);

        // then
        assertThat(persons.size()).isEqualTo(2);
}
```

输出的SQL：
```SQL
select
        person0_.id as id1_2_,
        person0_.age as age2_2_,
        person0_.birthday as birthday3_2_,
        person0_.company as company4_2_,
        person0_.id_card_id as id_card_7_2_,
        person0_.name as name5_2_,
        person0_.nick_name as nick_nam6_2_ 
    from
        person person0_ 
    where
        1=1
```

**Comment by wenhao** [comment]
经验证，确实是个Bug，最新的版本3.2.1已修改。
