### ISSUE TITLE
spring boot 2.0.0 + spring data jpa 2.0.5报错

### ISSUE THREAD

**Issue by fcjxxl** [wenhao/jpa-spec#20]
BetweenSpecification.java中的第25行
        return cb.between(from.get(field), range.getLowerBound(), range.getUpperBound());
报如下错误:
The method between(Expression<? extends Y>, Expression<? extends Y>, Expression<? extends Y>) in the type CriteriaBuilder is not applicable for the arguments (Path<Y>, Range.Bound, Range.Bound)

**Comment by wenhao** [comment]
可能不兼容，稍后我看一下。

**Comment by wenhao** [comment]
已经升级到3.2.0，依赖新版本的spring data jpa(2.0.5.RELEASE)。
Spring Data JPA 2.0.5.RELEASE更新了Range的方法。
