### ISSUE TITLE
between条件下Range的bug

### ISSUE THREAD

**Issue by lu920508536** [wenhao/jpa-spec#22]
Specification<MobileBasicEntity> spec = Specifications.<MobileBasicEntity>or()
		.eq(StringUtils.isNotBlank(mobileBasic.getCity()), "city", mobileBasic.getCity())
		.between(StringUtils.isNotBlank(dateInfo.getDateRange()), "createTime", Range.of(Range.Bound.inclusive(dateInfo.getStartDate()), Range.Bound.inclusive(dateInfo.getEndDate())))
		.build();

您好，StringUtils.isNotBlank(dateInfo.getDateRange())这一句我已经判空了，却还是进入后面Range.of(Range.Bound.inclusive(dateInfo.getStartDate())导致程序一直报 must not be null，
这个是什么原因呢！

**Comment by wenhao** [comment]
今天修复。没有测试条件为空的情况。

**Comment by lu920508536** [comment]
好的，修复好了，告诉我一下，我更新哈，谢谢！

**Comment by wenhao** [comment]
Spring Data内的Range类要去值不能为空。新版本3.2.3去掉了Range类。

**Comment by wenhao** [comment]
jcenter和maven central仓库都已更新。
