### ISSUE TITLE
使用sort属性找不到

### ISSUE THREAD

**Issue by kehuixu** [wenhao/jpa-spec#23]
findAll(specPatient,new PageRequest(0, 1, sort));
No property patient found

**Comment by kehuixu** [comment]
如果不加sort是能够正常返回的

**Comment by kehuixu** [comment]
发现问题，属性直接写成这样work_name,不适用Colum,使用sort会报错No property patient found

**Comment by wenhao** [comment]
把你的entity对象和相关代码贴出来看看。SortsTest.java测试文件里面的测试是跑过的，说明功能是正常的。
