### ISSUE TITLE
枚举属性

### ISSUE THREAD

**Issue by PrimaryKey3610** [wenhao/jpa-spec#28]
当类中存在枚举属性时,用一些EQ,NEQ等查询时,就会映射失败

**Comment by PrimaryKey3610** [comment]
1. 枚举类 
public enum  DeleteStates {
    Y("Y", 1),
    N("N", 2);
    private String  name;
    private Integer value;
}
2. user类 
public class User{
  private String id;
  
  @Enumerated(EnumType.STRING)
  @JSONField(serialize = false)
  private DeleteStates isDeleted;
  ...

}

3. 查询 
PredicateBuilder<User> predicateBuilder = Specifications.<User>and()
                .eq("isDeleted", "N");


这个时候isDeleted就会映射失败.

**Comment by wenhao** [comment]
PredicateBuilder predicateBuilder = Specifications.and()
.eq("isDeleted", DeleteStates.N);
试试？

**Comment by PrimaryKey3610** [comment]
非常感谢作者的回答. 由于时间的原因.当时确实没有试试.有点慌...
作者,我能提个扩展建议吗?   因为现在在使用这个组件的时候,都是后端知道业务的情况下,比如就查询EQ(name),EQ(remark),如果哪天业务改了.比如LIKE(name),LIKE(remark)的话,就需要手动改后台部署.
我有个想法.就是前端传输一种规定好的JSON 
如: [
          {
            "name":"name",
            "opt":"EQ",
             "value":"张三", 
         } ,{
            "name":"remark",
            "opt":"LIKE",
             "value":"张三", 
      } 
      ]
后台得到JSON串之后,  比如通过调用  service.buildSpecification(body,Class);  我感觉更加灵活一些...只是一种想法.

**Comment by wenhao** [comment]
你提的这个需求有点不太合适，使用eq还是like这个应该是你们业务确定的，而且不应该频繁改。如果有频繁改的需求，那就应该做成配置。可开关。

**Comment by luying777** [comment]
一个表中,二个字段,一个完成时间,应完成时间,如何过滤 完成时间>应完成时间,或完成时间<应完成时间
