### ISSUE TITLE
查询返回为空

### ISSUE THREAD

**Issue by baoqintian** [wenhao/jpa-spec#29]
![image](https://user-images.githubusercontent.com/26180936/50591257-9acf4100-0ec9-11e9-9c08-bd1ac164e171.png)

**Comment by wenhao** [comment]
不太明白，是数据库code1到5有数据，然后没查询出来 还是？你把最终查询的SQL日志打印出来看看？

**Comment by baoqintian** [comment]
我又试了试，可以查询出来。但是有一部分程序报错
![image](https://user-images.githubusercontent.com/26180936/50668910-0bc34580-0ffd-11e9-82ed-3b6931423400.png)
![image](https://user-images.githubusercontent.com/26180936/50668924-1ed61580-0ffd-11e9-91af-8068111473a7.png)

**Comment by wenhao** [comment]
> 我又试了试，可以查询出来。但是有一部分程序报错
> ![image](https://user-images.githubusercontent.com/26180936/50668910-0bc34580-0ffd-11e9-82ed-3b6931423400.png)
> ![image](https://user-images.githubusercontent.com/26180936/50668924-1ed61580-0ffd-11e9-91af-8068111473a7.png)

**这个只能你自己解决了，可能是你的工程里面有spring-data-jpa其他的版本吧**
