### ISSUE TITLE
关于封装的问题

### ISSUE THREAD

**Issue by PrimaryKey3610** [wenhao/jpa-spec#32]
#28   首先感谢作者的开源组件,用着很是方便, 之前 这个关于JSON的问题是我提出来的, 这两天没事写了下, https://www.jianshu.com/p/7cb952b6ee8f, 作者你感觉怎么样 .. 有啥好的意见可以交流.

**Comment by wenhao** [comment]
我先看看

**Comment by wenhao** [comment]
**想法还是挺好的**，如果你项目的所有查询都可以抽象成这样的话确实可以。我理解你是把在Repository这一层的SearchRequest对象Map到Specification的这一个逻辑往前移了，变成了Web的JSON请求直接就到了“Specification”。确实可以省去一部分的Map工作量，但是灵活性可能会差一点。
可能会有以下问题：
* 前端需要知道这些SQL的语法糖。可能希望SQL逻辑都应该被Repository这一层给封装了。
* 判断条件是否执行的condition有可能需要编写额外代码的，不一定都是null判断。

你觉得呢？

**Comment by PrimaryKey3610** [comment]
因为我们开发时,是后台出接口文档, 每次都会把JSON的参数,以及逻辑写的很清楚,所以前端只需要按照文档填写JSON就可以了. 这样确实很适用于form表单的查询. 至于其他的复杂逻辑,可能还是需要别的方式去处理.
