### ISSUE TITLE
一个表中,二个字段,一个完成时间,应完成时间,如何过滤

### ISSUE THREAD

**Issue by luying777** [wenhao/jpa-spec#33]
一个表中,二个字段,一个"完成时间",另一个"应完成时间",如何过滤 完成时间>应完成时间,或完成时间<应完成时间

**Comment by wenhao** [comment]
直接写@Query就可以了吧

**Comment by luying777** [comment]
@query 是可以解决,但是如果再加上动态条件的问题,也是不好处理了.
