### ISSUE TITLE
请问是否支持三级甚至更深层级查询？

### ISSUE THREAD

**Issue by ZhanRu** [wenhao/jpa-spec#49]
比如我现在可以通过applyUser.name  查询用户名为XXX的属性，然后我想通过类似的applyUser.company.id写法通过公司ID查询查询这个用户的公司ID为XXX的属性？

**Comment by wenhao** [comment]
这个有点难，建议写nativesql吧。毕竟在Spring JPA支持也不好。

**Comment by ZhanRu** [comment]
好吧 多谢回复
