### ISSUE TITLE
在判断日期eq的时候 存在问题

### ISSUE THREAD

**Issue by jiangweiguo** [wenhao/jpa-spec#6]
如果数据库中的日期是date类型的 使用eq的时候需要将日期的时分秒毫秒设置为0  希望加上

	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME, pattern = "yyyy-MM-dd HH:mm:ss")

这样的注解进行判断

**Comment by wenhao** [comment]
好的，尽快修复。

**Comment by wenhao** [comment]
你在描述下你的问题，我没明白。
如果数据库中是date类型，只有 年月日 ？为了兼容TIMESTAMP肯定时分秒都是要有的啊。而且这个是JPA原有的功能我并没有改什么。

**Comment by jiangweiguo** [comment]
@Test
	public void test4() {
		Calendar calendar = Calendar.getInstance();
		calendar.set(2017, 4, 11, 0, 0, 0);
		calendar.set(Calendar.MILLISECOND, 0);
		Specification<SrOrder> specification = Specifications.<SrOrder> and()//
				//.eq("sellDate", new Date())//
				.eq("sellDate", calendar.getTime())//数据库中的字段是date类型 必须将时间的时分秒毫秒设置为0才能查到
				.build();
		List<SrOrder> srOrder = srOrderRepository.findAll(specification);
		System.out.println(srOrder.size());
	}

**Comment by wenhao** [comment]
我写个测试吧，你在我的基础上改，看区别在哪？
```java
@Test
public void test_equal_date() throws ParseException
{
      // given
      Person jack = new PersonBuilder()
              .name("Jack")
              .age(18)
              .birthday(getDate("2017-12-12 08:30:10"))
              .build();
      personRepository.save(jack);

      // when
      Specification<Person> specification = Specifications.<Person>and()
              .eq("birthday", jack.getBirthday())
              .build();

      Person person = personRepository.findOne(specification);

      // then
      assertThat(person).isNotNull();
}

private Date getDate(String source) throws ParseException
{
      return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(source);
}
```

**Comment by jiangweiguo** [comment]
如果数据库里的birthday是date类型，那么'2017-12-12 08:30:10'存储到数据里的是'2017-12-12'，然后在查询的时候 使用'2017-12-12 08:30:10'这个是查询不到的吧？  只有将查询的参数的时分秒毫秒都设置为0才能查询到，查询的日期和数据库存储的一模一样才可以查到，我想的是在birthday上加上注解，用于区分是date还是datetime，在查询的date类型的时候，不用关注时分秒毫秒

**Comment by wenhao** [comment]
这个最好还是消费者来格式化Date之后，然后再做数据库查询吧。
