### ISSUE TITLE
问下我想查时间段支持吗

### ISSUE THREAD

**Issue by boboge** [wenhao/jpa-spec#8]
如大于等于某时间，小于等于某时间

**Comment by wenhao** [comment]
支持的

**Comment by boboge** [comment]
我用ge好像不行吧，麻烦写个示例

**Comment by wenhao** [comment]
详细描述你的需求，我给你写个测试

**Comment by boboge** [comment]
我实体对象里会有一个gmtCreated，在controller中会有两个参数startDate endDate,但是这两个参数是动态的可能都有，可能只有一个，我想通过你的插件动态生成sql，如gmtCreated>=startDate,或gmtCreated<=endDate,或者gmtCreated>=startDate and gmtCreated<=endDate

**Comment by boboge** [comment]
另外参数反正也是动态的，可以通过空判断实现

**Comment by wenhao** [comment]
今天中午看一下，昨天有点忙。

**Comment by boboge** [comment]
嗯

**Comment by wenhao** [comment]
目前确实不支持，是因为我限定了比较的类型必须是Number，这周内我把它修复一下。
谢谢反馈 ！

**Comment by boboge** [comment]
嗯，我看来源码应该只要加上那个specifiction的另外几个方法支持就行，更新了通知哈

**Comment by zhoujinliang** [comment]
我也需要这个功能，目前只有between，range，但是我的日期只需要大于或者只需要小于

**Comment by boboge** [comment]
是的我也是同样的需求

**Comment by wenhao** [comment]
已经实现了，今天就发布。可以使用ge、gt、le、lt和between进行时间的比较。

**Comment by wenhao** [comment]
已发布到jcenter

**Comment by boboge** [comment]
好的晚上试一下

**Comment by boboge** [comment]
好的晚上试一下
